# Generated by Django 5.1.3 on 2024-12-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testprogress',
            unique_together={('student', 'category', 'level', 'test_type')},
        ),
        migrations.AddField(
            model_name='testprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='testprogress',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='testprogress',
            name='completed',
        ),
    ]
