# Generated by Django 5.1.3 on 2024-12-29 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence', models.TextField(unique=True)),
                ('category', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('test_type', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
    ]
