# Generated by Django 5.1.3 on 2024-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='test_type',
        ),
        migrations.AddField(
            model_name='sentence',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
