# Generated by Django 5.1.3 on 2025-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testprofile',
            name='test_restarted',
            field=models.BooleanField(default=False),
        ),
    ]
